Element.create! number: 1, symbol: "H" , name: "Hydrogen"
Element.create! number: 2, symbol: "He", name: "Helium"
Element.create! number: 3, symbol: "Li", name: "Lithium"
Element.create! number: 4, symbol: "Be", name: "Berylium"
Element.create! number: 5, symbol: "B",  name: "Boron"
