source 'https://rubygems.org'

gem 'actionpack' # for Rails form helpers
gem 'activerecord-postgresql-adapter'
gem 'activeresource', require: 'active_resource'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'dynamic_form'
gem 'dynamic_form' # for error_messages_for
gem 'erubis' # for automatic escaping of HTML
gem 'haml'
gem 'haml-rails'
gem 'jbuilder', '~> 1.2'
gem 'jquery-rails'
gem 'meta_request'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'pg'
gem 'pony'
gem 'pry-debugger'
gem 'pry-doc'
gem 'pry-rails'
gem 'rack'
gem 'rack-flash3'
gem 'rails', '4.0.0'
gem 'rails-footnotes', github: "tommireinikainen/rails-footnotes",
  ref: "2f6f38808b052ba7e1b59107acdc6144a3ec448e", group: :development
gem 'rails_12factor'
gem 'rake_db_dump'
gem 'sass-rails', '~> 4.0.0'
gem 'sdoc', require: false
gem 'sinatra'
gem 'sinatra-footnotes'
gem 'sinatra_more'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'will_paginate', '~> 3.0.0'
